version: '2.3'
services:
  tema2:
    build: .
    ports:
      - "8080:8080"
    image: "tema2"
    
  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e
      MYSQL_DATABASE: lab1_db
    ports:
      - "3308:3306"
    volumes:
      - "./my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"

  admin:
    image: adminer
    ports:
    - 8080:8080 